### ISSUE TITLE
VCN crash on vcn notarize docker://$IMAGE

### ISSUE THREAD

**Issue by Sund3** [codenotary/vcn#146]
As part of our CI we do
vcn notarize docker://$IMAGE

Usually that works fine, but sometimes we get this error
.....
[K| Notarization in progress...
[K/ Notarization in progress...
[K
Size:	20 B
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xdbfd3c]

goroutine 1 [running]:
github.com/vchain-us/vcn/pkg/cmd/sign.sign(0xc0004f3600, 0x7ffc948ea3e1, 0x6, 0xc000044700, 0x6c, 0xc000286140, 0x40, 0x91e74ee, 0x0, 0x0, ...)
	/src/pkg/cmd/sign/sign.go:416 +0x65c
github.com/vchain-us/vcn/pkg/cmd/sign.runSignWithState(0xc000562580, 0xc00053ac00, 0x1, 0x1, 0x0, 0x0, 0x0)
	/src/pkg/cmd/sign/sign.go:318 +0xe3d
github.com/vchain-us/vcn/pkg/cmd/sign.makeCommand.func1(0xc000562580, 0xc00053ac00, 0x1, 0x1, 0x0, 0x0)
	/src/pkg/cmd/sign/sign.go:81 +0x52
github.com/spf13/cobra.(*Command).execute(0xc000562580, 0xc00053abe0, 0x1, 0x1, 0xc000562580, 0xc00053abe0)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0x17c54a0, 0xc0000a2900, 0x110b5f8, 0xc00056c2c0)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/vchain-us/vcn/pkg/cmd.Execute()
	/src/pkg/cmd/cmd.go:61 +0x53
main.main()
	/src/cmd/vcn/root.go:16 +0x25

We use the latest-docker image from docker hub to run this
Specifying
export VCN_USER=$VCN_USER
export VCN_PASSWORD=$VCN_PASSWORD
export VCN_NOTARIZATION_PASSWORD=$VCN_NOTARIZATION_PASSWORD
export VCN_OTP_EMPTY="true"

**Comment by vchaindz** [comment]
Can you give us some additional details please:

- what vcn version do you use?
- how often is "sometimes"? once a day, every x run

Thanks

**Comment by Sund3** [comment]
version - 0.9.4 - as I mentioned - https://hub.docker.com/layers/codenotary/vcn/latest-docker/images/sha256-2e2aca0006a37e397604cdd5a8049e18a26170734da2fb20af04b97229d27869?context=explore
Occurs every 10 runs or so
we run in parallel sometimes in our CI, but this doesn't happen only on parallel runs

**Comment by dmacvicar** [comment]
@Sund3 can you try with any of the builds in the bottom of this page?

https://github.com/codenotary/vcn/actions/runs/838991106
